/*
 * LoginWelcomePanel.java
 *
 * Created on __DATE__, __TIME__
 */

package cn.hncu.bookStore.login.ui;

/**
 * 
 * @author ³ÂºÆÏè
 *
 * @version 1.0  2016-4-20
 */
public class LoginWelcomePanel extends javax.swing.JPanel {

	/** Creates new form LoginWelcomePanel */
	public LoginWelcomePanel() {
		initComponents();
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	//GEN-BEGIN:initComponents
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		jLabel1 = new javax.swing.JLabel();

		setMinimumSize(new java.awt.Dimension(800, 600));
		setLayout(null);

		jLabel1.setFont(new java.awt.Font("Dialog", 1, 36));
		jLabel1.setForeground(new java.awt.Color(255, 0, 0));
		jLabel1.setText("\u6b22\u8fce\u767b\u5f55\uff0c\u592a\u9633\u6bcf\u5929\u90fd\u662f\u65b0\u7684\uff01\uff01");
		add(jLabel1);
		jLabel1.setBounds(100, 190, 590, 170);
	}// </editor-fold>
	//GEN-END:initComponents

	//GEN-BEGIN:variables
	// Variables declaration - do not modify
	private javax.swing.JLabel jLabel1;
	// End of variables declaration//GEN-END:variables

}