/*
 * StockListPanel.java
 *
 * Created on __DATE__, __TIME__
 */

package cn.hncu.bookStore.stock.ui;

import java.util.List;

import javax.swing.JFrame;

import cn.hncu.bookStore.stock.business.factory.StockEbiFactory;
import cn.hncu.bookStore.stock.vo.StockModel;

/**
 * 
 * @author ³ÂºÆÏè
 *
 * @version 1.0  2016-4-20
 */
public class StockListPanel extends javax.swing.JPanel {

	private JFrame mainFrame = null;

	/** Creates new form StockListPanel */
	public StockListPanel(JFrame mainFrame) {
		this.mainFrame = mainFrame;
		initComponents();
		myInitData();
	}

	public StockListPanel(JFrame mainFrame, List<StockModel> results) {
		this.mainFrame = mainFrame;
		initComponents();
		jListStocks.setListData(results.toArray());
	}

	private void myInitData() {
		List<StockModel> lists = StockEbiFactory.getStockEbi().getAll();
		jListStocks.setListData(lists.toArray());
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	//GEN-BEGIN:initComponents
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		jLabel1 = new javax.swing.JLabel();
		jScrollPane1 = new javax.swing.JScrollPane();
		jListStocks = new javax.swing.JList();
		btnQuery = new javax.swing.JButton();

		setMinimumSize(new java.awt.Dimension(800, 600));
		setLayout(null);

		jLabel1.setFont(new java.awt.Font("Î¢ÈíÑÅºÚ", 1, 48));
		jLabel1.setForeground(new java.awt.Color(255, 0, 0));
		jLabel1.setText("\u5e93\u5b58\u5217\u8868");
		add(jLabel1);
		jLabel1.setBounds(280, 0, 220, 90);

		jListStocks.setFont(new java.awt.Font("Î¢ÈíÑÅºÚ", 1, 18));
		jListStocks.setForeground(new java.awt.Color(0, 0, 153));
		jListStocks.setModel(new javax.swing.AbstractListModel() {
			String[] strings = { "" };

			public int getSize() {
				return strings.length;
			}

			public Object getElementAt(int i) {
				return strings[i];
			}
		});
		jScrollPane1.setViewportView(jListStocks);

		add(jScrollPane1);
		jScrollPane1.setBounds(120, 100, 520, 320);

		btnQuery.setFont(new java.awt.Font("Dialog", 1, 36));
		btnQuery.setForeground(new java.awt.Color(255, 0, 51));
		btnQuery.setText("\u67e5\u8be2\u5e93\u5b58");
		btnQuery.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btnQueryActionPerformed(evt);
			}
		});
		add(btnQuery);
		btnQuery.setBounds(270, 440, 190, 90);
	}// </editor-fold>
	//GEN-END:initComponents

	private void btnQueryActionPerformed(java.awt.event.ActionEvent evt) {
		mainFrame.setContentPane(new StockQueryPanel(mainFrame));
		mainFrame.validate();
	}

	//GEN-BEGIN:variables
	// Variables declaration - do not modify
	private javax.swing.JButton btnQuery;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JList jListStocks;
	private javax.swing.JScrollPane jScrollPane1;
	// End of variables declaration//GEN-END:variables

}