/*
 * StockQueryPanel.java
 *
 * Created on __DATE__, __TIME__
 */

package cn.hncu.bookStore.stock.ui;

import java.util.List;

import javax.swing.JFrame;
import javax.swing.JOptionPane;

import cn.hncu.bookStore.book.business.factory.BookEbiFactory;
import cn.hncu.bookStore.book.vo.BookModel;
import cn.hncu.bookStore.stock.business.factory.StockEbiFactory;
import cn.hncu.bookStore.stock.vo.StockModel;
import cn.hncu.bookStore.stock.vo.StockQueryModel;

/**
 * 
 * @author 陈浩翔
 *
 * @version 1.0  2016-4-20
 */
public class StockQueryPanel extends javax.swing.JPanel {

	private JFrame mainFrame = null;

	/** Creates new form StockQueryPanel 
	 * @param mainFrame */
	public StockQueryPanel(JFrame mainFrame) {
		this.mainFrame = mainFrame;
		initComponents();
		myInitData();
	}
	
	/**
	 * 初始化图书box
	 */
	private void myInitData() {
		List<BookModel> books = BookEbiFactory.getBookEbi().getAll();
		for(BookModel book:books){
			combBook.addItem(book.getName());
		}
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	//GEN-BEGIN:initComponents
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		jLabel1 = new javax.swing.JLabel();
		jLabel7 = new javax.swing.JLabel();
		tfdStockUuid = new javax.swing.JTextField();
		jLabel5 = new javax.swing.JLabel();
		combBook = new javax.swing.JComboBox();
		jLabel8 = new javax.swing.JLabel();
		tfdStockNum = new javax.swing.JTextField();
		jLabel11 = new javax.swing.JLabel();
		tfdStockNum2 = new javax.swing.JTextField();
		btnQuery = new javax.swing.JButton();
		btnBack = new javax.swing.JButton();

		setMinimumSize(new java.awt.Dimension(800, 600));
		setLayout(null);

		jLabel1.setFont(new java.awt.Font("Dialog", 1, 48));
		jLabel1.setForeground(new java.awt.Color(255, 0, 0));
		jLabel1.setText("\u5e93\u5b58\u67e5\u8be2");
		add(jLabel1);
		jLabel1.setBounds(270, 0, 230, 90);

		jLabel7.setFont(new java.awt.Font("微软雅黑", 0, 18));
		jLabel7.setText("\u5e93\u5b58\u7f16\u53f7:");
		add(jLabel7);
		jLabel7.setBounds(80, 160, 80, 30);
		add(tfdStockUuid);
		tfdStockUuid.setBounds(180, 160, 150, 30);

		jLabel5.setFont(new java.awt.Font("微软雅黑", 0, 18));
		jLabel5.setText("\u56fe\u4e66:");
		add(jLabel5);
		jLabel5.setBounds(430, 150, 50, 30);

		combBook.setFont(new java.awt.Font("Dialog", 1, 18));
		combBook.setModel(new javax.swing.DefaultComboBoxModel(
				new String[] { "查询所有" }));
		add(combBook);
		combBook.setBounds(490, 150, 190, 30);

		jLabel8.setFont(new java.awt.Font("微软雅黑", 0, 18));
		jLabel8.setText("\u5e93\u5b58\u6700\u5c0f\u6570\u91cf:");
		add(jLabel8);
		jLabel8.setBounds(50, 270, 140, 30);
		add(tfdStockNum);
		tfdStockNum.setBounds(180, 270, 150, 30);

		jLabel11.setFont(new java.awt.Font("微软雅黑", 0, 18));
		jLabel11.setText("\u5e93\u5b58\u6700\u5927\u6570\u91cf:");
		add(jLabel11);
		jLabel11.setBounds(360, 270, 120, 30);
		add(tfdStockNum2);
		tfdStockNum2.setBounds(490, 270, 190, 30);

		btnQuery.setFont(new java.awt.Font("Dialog", 1, 24));
		btnQuery.setForeground(new java.awt.Color(255, 0, 51));
		btnQuery.setText("\u67e5\u8be2");
		btnQuery.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btnQueryActionPerformed(evt);
			}
		});
		add(btnQuery);
		btnQuery.setBounds(140, 410, 120, 70);

		btnBack.setFont(new java.awt.Font("Dialog", 1, 24));
		btnBack.setForeground(new java.awt.Color(255, 0, 51));
		btnBack.setText("\u8fd4\u56de");
		btnBack.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btnBackActionPerformed(evt);
			}
		});
		add(btnBack);
		btnBack.setBounds(490, 410, 120, 70);
	}// </editor-fold>
	//GEN-END:initComponents

	private void btnQueryActionPerformed(java.awt.event.ActionEvent evt) {
		// 1收集参数(且验证输入有效性)
		//库存编号
		String uuid = tfdStockUuid.getText();
		//图书编号
		String bookUuid = null;
		if (combBook.getSelectedIndex() > 0) {
			bookUuid = BookEbiFactory.getBookEbi()
					.getBookByName(combBook.getSelectedItem().toString())
					.getUuid();
		}

		//库存最小数量
		int sumNum = 0;
		if (tfdStockNum.getText() != null
				&& tfdStockNum.getText().trim().length() > 0) {
			try {
				sumNum = Integer.parseInt(tfdStockNum.getText());
				if (sumNum < 0) {
					throw new NumberFormatException();
				}
			} catch (NumberFormatException e) {
				JOptionPane.showMessageDialog(mainFrame, "库存最小数量必须输入正整数!");
				return;
			}
		}

		//库存最大数量
		int sumNum2 = 0;
		if (tfdStockNum2.getText() != null
				&& tfdStockNum2.getText().trim().length() > 0) {
			try {
				sumNum2 = Integer.parseInt(tfdStockNum2.getText());
				if (sumNum2 < 0) {
					throw new NumberFormatException();
				}
			} catch (NumberFormatException e) {
				JOptionPane.showMessageDialog(mainFrame, "库存最大数量必须输入正整数!");
				return;
			}
		}

		// 2组织参数----StockQueryModel
		StockQueryModel sqm = new StockQueryModel();
		sqm.setUuid(uuid);
		sqm.setBookUuid(bookUuid);
		sqm.setSumNum(sumNum);
		sqm.setSumNum2(sumNum2);

		// 3调用逻辑层
		List<StockModel> results = StockEbiFactory.getStockEbi()
				.getByCondition(sqm);

		// 4返回到结果页面
		mainFrame.setContentPane(new StockListPanel(mainFrame, results));
		mainFrame.validate();
	}

	private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {
		back();
	}

	private void back() {
		mainFrame.setContentPane(new StockListPanel(mainFrame));
		mainFrame.validate();
	}

	//GEN-BEGIN:variables
	// Variables declaration - do not modify
	private javax.swing.JButton btnBack;
	private javax.swing.JButton btnQuery;
	private javax.swing.JComboBox combBook;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel11;
	private javax.swing.JLabel jLabel5;
	private javax.swing.JLabel jLabel7;
	private javax.swing.JLabel jLabel8;
	private javax.swing.JTextField tfdStockNum;
	private javax.swing.JTextField tfdStockNum2;
	private javax.swing.JTextField tfdStockUuid;
	// End of variables declaration//GEN-END:variables

}